### ISSUE TITLE
Ambiguous class provide a unique identifier

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#116]
With `1.6.0` and `SuperJson.registerClass(AuthenticationError, {identifier: "BlitzAuthenticationError"})`, I'm still getting the `Ambiguous class provide a unique identifier` warning.

```
$ blitz start

// ... stuff

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using external babel configuration from /Users/b/c/blitz2/examples/auth/.blitz/caches/dev/babel.config.js
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Ambiguous class "BlitzAuthenticationError", provide a unique identifier.
Ambiguous class "BlitzCSRFTokenMismatchError", provide a unique identifier.
Ambiguous class "BlitzAuthorizationError", provide a unique identifier.
Ambiguous class "BlitzNotFoundError", provide a unique identifier.
event - build page: /api/users/queries/getCurrentUser
```

You can reproduce this in the auth example app on this PR: https://github.com/blitz-js/blitz/pull/1828

**Comment by Skn0tt** [comment]
I suspect this to be b/c the Next compiler two multiple passes for the files that are contain `BlitzAuthenticationError` etc.
Because they have different identities (at least during compilation), the warning is printed. Tbh, I see this as more of a Next-Problem than SuperJSON-specific. Still, we can think about ways to hide that warning during build. Do you have an idea?

**Comment by flybayer** [comment]
@Skn0tt idk, but it's really bad UX. 

I guess my suggestion is hide this warning by default, but provide a way, maybe with node `debug` module or env var to enable the warning in case someone is trying to debug something.

**Comment by samtgarson** [comment]
Hey folks! Related question/issue: I'm getting this log too on 1.6.0 for every page when I run the next app in development... But when I run it in production I get a fatal crash with `Trying to deserialize unknown class` in the _client_ console (suggesting to me that the the classes were recognised server side for serialisation, but not client side)

Is there a recommended place to put the calls to `registerClass` to ensure it only runs once and on both client and server sides, at the right time (i.e. before (de)serialisation)?

I've tried placing it in the files where the classes are defined next to the class definitions, and tried calling it in _app too, but with no luck...

If this is a separate issue I can open one and try to provide a recreation. Thanks!

**Comment by samtgarson** [comment]
> Hey folks! Related question/issue: I'm getting this log too on 1.6.0 for every page when I run the next app in development... But when I run it in production I get a fatal crash with `Trying to deserialize unknown class` in the _client_ console (suggesting to me that the the classes were recognised server side for serialisation, but not client side)
> 
> Is there a recommended place to put the calls to `registerClass` to ensure it only runs once and on both client and server sides, at the right time (i.e. before (de)serialisation)?
> 
> I've tried placing it in the files where the classes are defined next to the class definitions, and tried calling it in _app too, but with no luck...
> 
> If this is a separate issue I can open one and try to provide a recreation. Thanks!
> 
> (worth mentioning—we're using the babel plugin too)

Turned out to be an issue with minification, adding an `identifier` to the `registerClass` call fixed it. That stuff isn't documented yet but this would be a good one to add there whenever that happens.

I'll stop derailing this issue now 😅

**Comment by Skn0tt** [comment]
@samtgarson thanks for reporting that! See #117.
