### ISSUE TITLE
Docs out of date for serialize?

### ISSUE THREAD

**Issue by goleary** [blitz-js/superjson#134]
When I use the serialize example from the docs the result meta prop is different than what's seen in the [Readme](https://github.com/blitz-js/superjson#advanced-usage).

example:
```ts
const object = {
  normal: 'string',
  timestamp: new Date(),
  test: /superjson/,
};

const { json, meta } = superjson.serialize(object);

/*
json = {
  normal: 'string',
  timestamp: "2020-06-20T04:56:50.293Z",
  test: "/blitz/",
};

// note that `normal` is not included here; `meta` only has special cases
meta = {
  timestamp: ['date'],
  test: ['regexp'],
};
*/
```
result
```json
{
  "json": {
    "normal": "string",
    "timestamp": "2021-04-22T16:15:17.357Z",
    "test": "/superjson/",
  },
  "meta": {
    "values": {
      "timestamp": ["Date"],
      "test": ["regexp"]
    }
  }
}
```

the difference is the additional nested `values` prop

https://runkit.com/goleary/60819f9934243b001c2071d1

**Comment by Skn0tt** [comment]
Good catch! Fixed in https://github.com/blitz-js/superjson/commit/b58faa01f09b8f9c210889f1c58e14bdd606aa43.

@all-contributors please add @goleary for docs

**Comment by goleary** [comment]
Thanks for the quick fix!
