### ISSUE TITLE
Add all-contributors

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#14]
https://allcontributors.org/

**Comment by merelinguist** [comment]
@all-contributors please add merelinguist for code doc design

**Comment by merelinguist** [comment]
@all-contributors please add Skn0tt for code ideas

**Comment by merelinguist** [comment]
@all-contributors please add flybayer for ideas

**Comment by Skn0tt** [comment]
@all-contributors please add mrleebo for test code

**Comment by merelinguist** [comment]
@all-contributors please add Skn0tt for test

**Comment by merelinguist** [comment]
@all-contributors please add merelinguist for test
