### ISSUE TITLE
`mongodb` can't be imported on the client

### ISSUE THREAD

**Issue by italodeandra** [blitz-js/superjson#147]
When using the example from https://github.com/blitz-js/superjson/issues/71

I'm getting the following error `Error: Trying to deserialize unknown custom value`.

That's probably because `mongodb` can't be imported on the client. Can you give me a light on how do I make this work with NextJS?

_Originally posted by @italodeandra in https://github.com/blitz-js/superjson/issues/71#issuecomment-846603353_

**Comment by Skn0tt** [comment]
Hi @italodeandra! What do you mean by „when using the example“? What are you trying to serialize? Please post a reproduction case.

**Comment by italodeandra** [comment]
I'm trying to serialize an ObjectID. My reproduction is using your example on a NextJS application.

Do you have any example of using it? Perhaps I'm doing something wrong.

**Comment by Skn0tt** [comment]
There's a passing test for it here: https://github.com/blitz-js/superjson/blob/af5af550cfaa3a2bb79efce264326a7fbd222b62/src/index.test.ts#L454

**Comment by italodeandra** [comment]
The problem is specific for NextJS when you're using SSR. I'll try to create a codesandbox.

**Comment by italodeandra** [comment]
I created the following example (I ended up creating a minimal reproduction repository instead of a codesandbox): https://github.com/italodeandra/superjson-issue-147
You can run it without a database since I'm using a memory mongo server.

This is the file with the entire implementation: https://github.com/italodeandra/superjson-issue-147/blob/main/pages/index.tsx

But also note these two lines on the `package.json` where I tell babel to not add `mongoose` or `mongodb` to the frontend: https://github.com/italodeandra/superjson-issue-147/blob/a2d3ad0b9ccc17448c639c3468e2d98ce3130539/package.json#L27-L28

Here you can see my workaround: https://github.com/italodeandra/superjson-issue-147/blob/a2d3ad0b9ccc17448c639c3468e2d98ce3130539/pages/index.tsx#L13

ObjectID class is only available on the backend since we removed mongo from the frontend.

**Comment by Skn0tt** [comment]
Sorry for the delay, looking into it now.

**Comment by Skn0tt** [comment]
Now I understand the problem! It was in your original issue description all along: `mongodb can't be imported on the client`. If that's the case, then SuperJSON sadly can't help :( SuperJSON is made to preserve types during the transport from client to server. That requires the types to be available on both client and server. So if `mongodb` isn't isomorph (which makes sense!), then we're out of luck here.

**Comment by Skn0tt** [comment]
Your workaround essentially turns off all of SuperJSON's typing benefits. I'd suggest manually transforming ObjectIDs into strings, that keeps you from having to specify a custom type - it'll also allow you to drop the `browser: { mongoose: false }` statement, since then Next.js can correctly eliminate MongoDB from your client bundle.

**Comment by italodeandra** [comment]
I fixed it. Instead of importing from `mongodb` you should import from `bson`.

```ts
import { ObjectID } from "bson";
```

`bson` is a peer dependency from the `mongodb` driver and is where the **ObjectId** is from.
