### ISSUE TITLE
[HELP] Hooks with default exports stop working

### ISSUE THREAD

**Issue by aminick** [blitz-js/superjson#153]
I am working with Next.js, after adding `["superjson-next"]`

All hooks that uses default exports, will result in error, when imported in page components.

``` TSX
// ./pages/somepage.tsx
import useCustomHook from '.....'  <-- default import

const SomePage = () => {
  const foo = useCustomHook()

  foo() <-- ERROR

  ....
}
```

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5182324/133989476-ec886ecf-37c8-4cf6-a5b6-73b72c7dea13.png">

**Comment by Skn0tt** [comment]
Hi @aminick! Could you provide a reproduction repository for this? That'd make it a lot easier for me to help you.

**Comment by aminick** [comment]
@Skn0tt I am still trying to reproduce it in a green field repo, but with no luck. 
But I do have a few more findings and hopefully it rings bells for you.

First, the imported hooks that cause errors have a signature like 
```
F WithSuperJSON(props)
```

These hooks are imported from a folder under `/src/pages` for example
`/src/pages/SomeComponent/hooks/useSomeHooks`. These hooks are also default exports.
(In my application I also have a `/pages` folder at root)

As soon as I move it to another folder, lets say `/src/hooks/useSomeHooks`, everything is back to normal.

I suspect this could be caused by how Next.JS parses default exports under `pages` folder? or does SuperJSON babel have special rules for default exports under `pages`  or `src/pages` folder.

**Comment by flybayer** [comment]
> I suspect this could be caused by how Next.JS parses default exports under pages folder? or does SuperJSON babel have special rules for default exports under pages or src/pages folder.

@aminick yes. All files inside `pages` must be a page file. So you need to keep your hooks in another folder, as I see you tried.

**Comment by aminick** [comment]
@flybayer True, this confused me in the first place because I have both `pages` and `src/pages` folder, and my hooks are exported from `src/pages`. As quoted from Next.js Doc, `src/pages` should be ignored in this case. 
But apparently it's not 'ignore' completely.
