### ISSUE TITLE
`Invalid HMR message` `Error: No router instance found`

### ISSUE THREAD

**Issue by italodeandra** [blitz-js/superjson#161]
I'm getting this error for just adding the follow code to my `_app.js` file:

```tsx
import { ObjectId } from "bson";
import SuperJSON from "superjson";
SuperJSON.registerCustom(
  {
    isApplicable: (v) => v instanceof ObjectId,
    serialize: (v) => v.toHexString(),
    deserialize: (v) => new ObjectId(v)
  },
  "objectid"
);
```

This only happens on the first load of the page. Hot reloads after it won't trigger the error again.

Here's the sandbox showing the error and you can also remove this part of the code to see the error gone:

https://codesandbox.io/s/broken-sun-xo00m?file=/pages/_app.js

Note: you need to reload the codesandbox browser page to see the error gone (or appear if you add this code back again).

I have no idea how to fix this and it's getting on my nerves 😂.

My theory is that it might be related to the latest `next` version, since this error showed up only on my latest project with updated dependencies (I like to start fresh). Or perhaps `mui` is the problem. Because (weirdly) if you remove the `ThemeProvider` it also "removes" the error.

I could submit this same issue on mui's repo, but since superjson was the first thing I removed that also removed the error and because superjson is the closest thing I have with routing (thus the message error) compared to a context provider of a theme object, I decided to post here first and see if someone else can help me come to a solution.

-- Edit:

I want to point out that I am not sure that superjson is causing it. It was just the first code piece that when removing the error disappears. The second being the `ThemeProvider`.

**Comment by Skn0tt** [comment]
Hi Italo! I cannot reproduce the error using the codesandbox. Can you verify this is still happening for you, and possibly send a series of exact steps (or even a screencast!) on how to reproduce this?

**Comment by italodeandra** [comment]
Holy shit the message is gone on the codesandbox. I didn't change anything, but the `package.json` file uses the `latest` version of the packages, so they must have been updated automatically on the sandbox.

I'll try updating everything.

**Comment by italodeandra** [comment]
Updating from `12.0.5-canary.5` to `12.0.5-canary.8` seems to have fixed it.

https://user-images.githubusercontent.com/19225266/142995285-88cad2be-e301-4bf1-adb0-3d1f5c05bafb.mp4

So it wasn't actually related to `superjson`, sorry about that.
