### ISSUE TITLE
Typo in PrimitveJSONValue type

### ISSUE THREAD

**Issue by icflorescu** [blitz-js/superjson#168]
There's a typo in PrimitveJSONValue type here:

https://github.com/blitz-js/superjson/blob/c5bee351d2e25821600cd8e04b018e7c423b9f77/src/types.ts#L6

I could come up with a PR to fix it if needed, but I have no idea on how this should be handled so it won't become a breaking change.

**Comment by Skn0tt** [comment]
The type isn't exported anywhere consumable from clients, so it should be fine to just rename it :) Opened a PR!
