### ISSUE TITLE
[HELP] registering errors classes - different behavior under dev and build

### ISSUE THREAD

**Issue by tomADC443** [blitz-js/superjson#189]
The goal is to register a class via superJson on the server and then use it in the client. I have registered the error class via superJson in the _app file. This works just fine when I build the app (yarn build && yarn blitz start). The problem is in local dev mode (yarn dev) I have to register the error class via superJson on the server and not on the client. Is the build or minification process causing the difference? How to set it up so that it works for both? 

### The following works for dev: 
even if I don't register the error class on the client I still have access to it. 

```js
//error class:
import SuperJson from "superjson"

export class DeactivatedError extends Error {
  name = "DeactivatedError"
  constructor(){
    super()
  }
}
//with registration only in this file not in _app 
SuperJson.registerClass(DeactivatedError)
```

### This works for build: 
```js
//error class:
export class DeactivatedError extends Error {
  name = "DeactivatedError"
  constructor(){
    super()
  }
 //only works if there is no registration here but instead in _app.tsx
}
```
```js
// _app.tsx
//...
import SuperJson from "superjson"
import { DeactivatedError } from "app/auth/DeactivatedError"
SuperJson.registerClass(DeactivatedError,"DeactivatedError")
```

--- 
This is how I use the class in the front end in both cases: 
```js
if (error instanceof DeactivatedError) {
//...
}
```

**Comment by Skn0tt** [comment]
Hmm - we're recommending to put the `.registerClass` call right below the class definition, because pretty much every use of said class (e.g. `instanceof DeactivatedError`) will cause that `.registerClass` call the be included in the bundle. Not sure why this doesn't work in this case. Could you provide a minimal reproduction repository so we can reproduce? cc @beerose, do you have an idea if there's any bundling step that could cause this?

**Comment by tomADC443** [comment]
Thx. The problem with the additional registration in the client is also described [here](https://github.com/blitz-js/superjson/issues/116#issuecomment-774011336)
The error I am getting in the client when not registering the class in _app.tsx is the same as in the linked issue comment: `Trying to deserialize unknown class`
I am not sure if I can reproduce this in an example repo in a reasonable amount of time but I will try.
