### ISSUE TITLE
Pretty Printing

### ISSUE THREAD

**Issue by Zamiell** [blitz-js/superjson#222]
Hello, and thanks for the library.

With normal `JSON.stringify`, I can create pretty output like so:

```ts
console.log(JSON.stringify(request, undefined, 2));
```

I would like to emulate this behavior, but with superjson.

I imagine that the API could be changed from:

```ts
static stringify: (object: SuperJSONValue) => string;
```

To something like:

```ts
class StringifyOptions {
  pretty = false;
}

static stringify: (object: SuperJSONValue, options = new StringifyOptions()) => string;
```

Or, more simply, but less flexible for future additions:

```ts
static stringify: (object: SuperJSONValue, pretty = false) => string;
```

**Comment by Skn0tt** [comment]
Hi @Zamiell! Pretty-Printing is out-of-scope for SuperJSON. If you want to prettify your output, you could do the following:

```ts
JSON.stringify(SuperJSON.serialize(request), undefined, 2)
```

Does that solve your problem?

**Comment by Zamiell** [comment]
Ok. I'll close this issue then, thank you for the quick response.
