### ISSUE TITLE
are superjson strings stable/deterministic?

### ISSUE THREAD

**Issue by smolattack** [blitz-js/superjson#226]
```ts
import {stringify} from "superjson"

const str = stringify({a: 1, b:2})
// str is '{"json":{"a":1,"b":2}}'
```
Could `str` ever be '{"json":{"b":2,"a":1}}'?

Thanks

**Comment by Skn0tt** [comment]
I wouldn't depend on that, since it depends on the behaviour of a number of platform primitives like `JSON.stringify` or `Object.entries`, which could be different e.g. between Node.js and Deno.
