### ISSUE TITLE
Support async ?

### ISSUE THREAD

**Issue by wenerme** [blitz-js/superjson#233]
add `*Async` api, when using async, will also include `registerCustomeAsync` hook to serialize & deserialize.

**Why**

When using in server size, I want to serialize File and Blob to base64, this requires async process.

**Comment by wenerme** [comment]
@Skn0tt But not only Buffer, e.g. I can serialize FormData to/from json, FormData may contain File, witch contain Blob/Buffer. Serialized FormData can saved to db as request cache, I can replay the request or for audit.

**Comment by vitorcamachoo** [comment]
@wenerme I am still looking for a solution to serialise Blob/File present in a FormData. Without having a way to serialise and deserialise async methods, this looks unreachable. Did you find a solution to that?

**Comment by vitorcamachoo** [comment]
My use case is that I need to save a specific structure in the IndexedDB for future sync and since IndexedDB already allows to persist the File type, to have this working I created a custom serialiser to bypass the File type:
```tsx
// @ts-expect-error
// Bypass File (de)serialisation because IndexedDB already support File type
superjson.registerCustom<File, File>(
  {
    isApplicable: (v): v is File => v instanceof File,
    serialize: (v) => v,
    deserialize: (v) => v,
  },
  'file'
);

Couldn't find other way to do this cleaner.
```

**Comment by duduindo** [comment]
#### File to string

```js
const file = new File(["foo"], "foo.txt", { type: "text/plain" })

const url = URL.createObjectURL(file)

const xhr = new XMLHttpRequest()

xhr.open('GET', url, false)
xhr.send()

console.assert(xhr.response === "foo")
```

#### Response to buffer

```ts
const uint8 = Uint8Array.from(xhr.response, (c: string) => c.charCodeAt(0))

console.assert(uint8.buffer instanceof ArrayBuffer)
```


Source: https://github.com/ungap/structured-clone/issues/9#issue-1340967971
