### ISSUE TITLE
registerCustom types seems busted?

### ISSUE THREAD

**Issue by gflarity** [blitz-js/superjson#236]
I'm really confused. 
The following works fine:

```TypeScript
superJSON.registerCustom<Decimal, string>(
  {
    isApplicable: (v): v is Decimal => Decimal.isDecimal(v),
    serialize: v => v.toJSON(),
    deserialize: v => new Decimal(v),
  },
  'decimal.js'
);

```

However for my own custom transform I had to coerce types as they were off:

1) the out from  serialize was actually a expected to be a javascript object, not a string
2) the input to deserialize was actually an already deserialized object. 

```

function moneyToJSON(money: Money): any {
  const str = {amountCents: moneyToCents(money), currencyCode: getCurrency(money).code}
  return str;
}

function moneyFromJSON(v: any ): Money {
  const { amountCents, currencyCode} = v as { amountCents: string, currencyCode: string}
  return money(BigInt(amountCents), currencyCode as CurrencyCode)
}


superJSON.registerCustom<Money,string>(
  {
    isApplicable: (v): v is Money => isMoney(v),
    serialize: v => moneyToJSON(v),
    deserialize: v => moneyFromJSON(v),
  },
  'Money'
);

**Comment by gflarity** [comment]
So I think I'm closer to understanding, but this is more sane: 

```TypeScript
function moneyFromJSON(v: any ): Money {
  const { amountCents, currencyCode} = v as { amountCents: string, currencyCode: string}
  return money(BigInt(amountCents), currencyCode as CurrencyCode)
}


function moneyToJSON(money: Money): { amountCents: string, currencyCode: string} {
  return { amountCents: moneyToCents(money).toString(), currencyCode: getCurrency(money).code}
}

superJSON.registerCustom<Money,{ amountCents: string, currencyCode: string}>(
  {
    isApplicable: (v): v is Money => isMoney(v),
    serialize: v => moneyToJSON(v),
    deserialize: v => moneyFromJSON(v),
  },
  'Money'
);
```

I think maybe some more documentation is needed here. I'd happily submit a PR but I just don't understand what it should say yet.

**Comment by Skn0tt** [comment]
There's examples for custom serializers that output to string here:

- https://github.com/blitz-js/superjson/blob/abc5a9c07f8147d6b6f976e3fa59e78f8931cbe5/src/index.test.ts#L497
- https://github.com/blitz-js/superjson/blob/abc5a9c07f8147d6b6f976e3fa59e78f8931cbe5/src/index.test.ts#L522

It looks like you already found the second one.

You mention that a plain old javascript object needs to be used, I don't think that's true from those tests. If you believe there's a bug here, i'd very much appreciate a reproduction test!

Apart from this, a docs PR would be greatly appreciated. Maybe you could add a section to the README that has an example snippet, and talks about how it's used in general?
