### ISSUE TITLE
Add option to configure `replacer/reviver` to `JSON.stringify()`/`JSON.parse()`

### ISSUE THREAD

**Issue by skoshx** [blitz-js/superjson#240]
To work around some of the limitations of SuperJSON (like erroring when stringifying DOM events), I created a patch of SuperJSON that allows us to pass in the `replacer` and `reviver` function.

```typescript
type Replacer = (key: string, value: any) => any;

stringify(object: SuperJSONValue, replacer?: Replacer): string {
  return JSON.stringify(this.serialize(object), replacer);
}
```

Would this be possible to add as an optional option to the `stringify` & `parse` functions? I don't think this addition would add any more complexity to the codebase nor add any extra maintenance work.

I would be glad to create a Pull Request for this.

**Comment by Skn0tt** [comment]
Hi @skoshx! I'd like to keep SuperJSON's API surface area as small as possible, so i'm hesitant to add more parameters - especially when it's really easy to make use of them in user-land, as you showed in your snippet.

I see we already talked briefly about DOM events in https://github.com/blitz-js/superjson/issues/232, but for some reason I didn't suggest you to look at using `SuperJSON.registerCustom`. Have you tried using that for your usecase? If it doesn't work, could you outline how `replacer` addresses your needs?
