### ISSUE TITLE
ESM entrypoint isn't functional

### ISSUE THREAD

**Issue by acidoxee** [blitz-js/superjson#260]
The files in `dist/esm` are not valid ESM because:

- The folder is missing a `package.json` with `{ "type": "module" }` in it, OR files use a `.js` extension instead of `.mjs` (since the closest `package.json` states the package is using CJS)
- Relative imports in those files don't have an extension

This causes esbuild (for my case) and maybe other bundlers to discard this entrypoint and fallback to the CJS one instead (TypeScript resolution also points towards the CJS entrypoint, even when consumed from ESM code).

Do you think you might be able to fix the entrypoint to make ESM code able to consume ESM from your package as well? 🙏

**Comment by Skn0tt** [comment]
Thanks for reporting this! This sounds like a regression to me. I’m not in office until beginning of next week, but will take a look then.

**Comment by Skn0tt** [comment]
Released a pure ESM version in https://github.com/blitz-js/superjson/releases/tag/v2.0.0, let me know if that works for you!

**Comment by acidoxee** [comment]
I'm currently assessing whether this breaks something or not in my app, but what's sure is that esbuild now properly leverages ESM for `superjson` and its dependencies 🥳

![image](https://github.com/blitz-js/superjson/assets/23697296/fa21ac8f-57a4-4628-8053-4048f79a6a62)
![image](https://github.com/blitz-js/superjson/assets/23697296/c4cbdeca-b57f-42e0-ac7d-b8c5af30fcd1)
![image](https://github.com/blitz-js/superjson/assets/23697296/fc80202e-2f39-4d5b-a76c-72a8aefe7c4b)

I believe going ESM-only is the right move for most libs, otherwise people would rarely have any real incentive to move away from CJS. Anyway, thanks a lot for your quick reaction and fix!
