### ISSUE TITLE
Trying to use it with ofetch

### ISSUE THREAD

**Issue by digoburigo** [blitz-js/superjson#278]
I'm trying to use `superjson` with [ofetch](https://github.com/unjs/ofetch)
Is there something specific to make superjson work with this fetch alternative?
```ts
const ofetchOptions: FetchOptions = {
  baseURL: 'https://jsonplaceholder.typicode.com',
  parseResponse: superjson.parse, // this don't work
};
const api = ofetch.create(ofetchOptions);
```

Already open an [issue](https://github.com/unjs/ofetch/issues/329) in their repo.

**Comment by Skn0tt** [comment]
Hey @digoburigo! You're holding it wrong. The typicode API doesn't return SuperJSON, but normal JSON. That's why SuperJSON will return `undefined`. 

What are you trying to achieve? If the goal is to parse the incoming JSON, use `parseResponse: JSON.parse` instead.

**Comment by digoburigo** [comment]
Yes. I tried doing something that it's not possible. That is returning a superjson from a normal json response. That is not the purpose of this library. Sorry for the confusion.
