### ISSUE TITLE
Backwards compatibility with JSON

### ISSUE THREAD

**Issue by NMinhNguyen** [blitz-js/superjson#282]
Would it be possible to use `superjson` as a drop-in replacement for JSON, especially where you have some existing JSON (e.g. persisted), and you’d want it to be deserialised by `superjson`? Without native support for this, my worry is that consumers would either need to migrate all their JSON blobs to the `superjson` format, or write a custom serialise/deserialise function on top (e.g. with a top-level key such as `"__superjson__": "v1"` to know whether to parse via `JSON.parse` or `superjson`). In other words, I’d expect `superjson.parse(JSON.stringify(value))` to work - then it would truly be a superset of JSON.

**Comment by Skn0tt** [comment]
Hey! The "SuperSet of JSON" claim refers to the fact that it supports a superset of the datatypes that JSON support, not to its specific output format.

> write a custom serialise/deserialise function on top

That's what I'd recommend to do. If you're doing a migration, chances are that you'll have specific logic around it already, and that should contain the logic around using SuperJSON / JSON.

If we put this logic into SuperJSON itself, it would make it more complex to reason about, for no real advantage.

Here's a function that could work for the migration:

```ts
function parseJSONorSuperJSON(value: string) {
   const result = JSON.parse(value)
   return "json" in result
     ? SuperJSON.deserialize(result)
     : result
}
```

**Comment by gabimoncha** [comment]
would help a lot if you also handle any possible errors

```ts
function parseJSONorSuperJSON(value: string) {
  try {
    const result = JSON.parse(value);
    return 'json' in result ? SuperJSON.deserialize(result) : result;
  } catch (error) {
    // console or throw
    return result;
  }
}
```
