### ISSUE TITLE
Any plans for TypedArray?

### ISSUE THREAD

**Issue by aryzing** [blitz-js/superjson#285]
Any plans on supporting [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray)? Would be great for apps which need raw data, especially common in IoT and crypto.

**Comment by Skn0tt** [comment]
Hi @aryzing! SuperJSON already has support for typed arrays. Here's the unit test for it: https://github.com/blitz-js/superjson/blob/0130a809f87df142b5e190e1b519be0c0280fb16/src/index.test.ts#L611-L626

Maybe we should add it to the README!

**Comment by aryzing** [comment]
Great! Didn't dig into the code and opened the issue based on the README, which [didn't mention typed arrays](https://github.com/blitz-js/superjson/blob/0130a809f87df142b5e190e1b519be0c0280fb16/README.md?plain=1#L240). Thanks for letting me know :)
