### ISSUE TITLE
An error occurs when serializing the array with un-serialize-data

### ISSUE THREAD

**Issue by lwt09** [blitz-js/superjson#288]
An error occurs when executing the code below
`superjson.stringify({ data: ['data1', new Error('test')] })`

version; "superjson": "^2.2.1"

<img width="535" alt="image" src="https://github.com/blitz-js/superjson/assets/55039185/4087e7fa-ecb3-4685-b979-1eba950e3611">

<img width="413" alt="image" src="https://github.com/blitz-js/superjson/assets/55039185/8d305b69-d9bb-4e42-b166-1cb9eaed53d4">

**Comment by Skn0tt** [comment]
In what environment are you executing this? Is it Node, a Browser, Bun, …?

**Comment by lwt09** [comment]
> In what environment are you executing this? Is it Node, a Browser, Bun, …?您是在什么环境中执行这个操作？是在 Node、浏览器、Bun 等环境中吗？

I'm very sorry, the problem has been solved. The environment I'm running does not support URL... It's a castrated version of the JS environment.
