### ISSUE TITLE
Deserialize should accept `undefined`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#48]
Superjson currently throws an error if you try to `deserialize({json: undefined})`.

I think it should be a bit more permissive, and if input is undefined, return undefined.

Check out this ugly code I have to write because it doesn't do that 😄
https://github.com/blitz-js/blitz/pull/836/files#diff-6ee56009d994095b978bcddd01afafd8L65-L66

**Comment by jorisre** [comment]
@Skn0tt This issue is fixed and can be close :)

**Comment by Skn0tt** [comment]
You're right! Thanks for the heads up :D
