### ISSUE TITLE
Serialize should accept `unknown` type

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#49]
Currently you have to call serialize like this, otherwise TS errors.

```ts
superjson.serialize(result as any)
```

**Comment by jorisre** [comment]
Hi @flybayer 
I tried to use `superjson.serialize` with a parameter typed as `unknown` and I'm not getting error. Where I'm wrong ?

**Comment by flybayer** [comment]
This might have been fixed already 🤔

**Comment by ftonato** [comment]
Hey guys,

I just did the following test:

```typescript
import superjson from "superjson";

type Freak = {
  name: string,
  age: unknown
}

const person: Freak = {
  name: '@ftonato',
  age: 1,
};

const { json } = superjson.serialize(person);

console.log('Serialized values: ', json); // Serialized values:  { name: "@ftonato", age: 1 }
```

Is working as expected, but I will create an test with this scenario :)
