### ISSUE TITLE
ERROR Error: Not a valid SuperJSON payload.

### ISSUE THREAD

**Issue by xinqm0217** [blitz-js/superjson#56]
const obj = {
   e: 123,
   f: 'str2',
};
const str = JSON.stringify(obj);
const result = superjson.parse(str);

ERROR Error: Not a valid SuperJSON payload.

**Comment by Skn0tt** [comment]
You'll need to stringify using SuperJSON:
```ts
const obj = {
  e: 123,
  f: 'str2',
};
const str = SuperJSON.stringify(obj); // 👈 you used JSON instead of SuperJSON
const result = superjson.parse(str);
```
