### ISSUE TITLE
Custom error serialization broken in 1.4.0

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#80]
I added `registerClass` in Blitz internals so that blitz custom errors are fully deserialized on the client to work with `instanceof`. This works great in 1.3.0, but breaks in 1.4.0.

In 1.4.0, the custom error is serialized as a plain Error instead of the custom error class.

Also, I noticed that in 1.4.0 extra static properties on the error are not serialized. In 1.3.0 blitz errors have `statusCode` properly serialized, but in `1.4.0` they don't.

Related Blitz PR: https://github.com/blitz-js/blitz/pull/1414

**Comment by Skn0tt** [comment]
I've started to look into this in #81, but faced a weird error:

```ts
class CustomError extends Error {
  constructor(public readonly customProperty: number) {
    super("I'm a custom error");
  }
}

expect(new CustomError(10)).toBeInstanceOf(CustomError)
```

For some weird reason, this fails. I've yet to find out why.
